# Generated by Django 4.1.5 on 2023-01-15 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_id_alter_booking_no_of_guest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='No_of_guest',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Inventory',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
